language: elixir

dist: trusty
sudo: required
services:
  - docker

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix compile
  - MIX_ENV=test mix compile

branches:
  only:
    - master
    - stable
    - /^rel\-\d+\.\d+$/
    - /^\d+\.\d+\.\d+([a-z0-9\-\+])*/

script:
  .travis/script.sh $PRESET

after_script:
  mix inch.report

after_success:
  - .travis/docker.sh

elixir:
  - 1.4.0
otp_release:
  - 19.2
  - 18.3
env:
  - PRESET=test

matrix:
  include:
    - otp_release: 19.2
      elixir: 1.4.0
      env: PRESET=dialyzer

cache:
  directories:
      - .dialyzer
